version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    environment:
      DOCKER_SERVER: $REGISTRY_SERVER
      IMAGE_NAME: $IMAGE_NAME
    steps:
      - checkout:
          post:
            - git fetch --all
      - setup_remote_docker
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --freeze-lockfile
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run linting
          command: yarn run lint
      - run:
          name: Run Test
          command: yarn run test
      - run:
          name: Run Build
          command: yarn run build
      - store_artifacts:
          path: build/
      - run:
          name: Build and push Docker image
          command: |
            echo $CIRCLE_BUILD_NUM "circle build num"
            echo $CIRCLE_BRANCH "CIRCLE_BRANCH "
            echo $REGISTRY_SERVER "REGISTRY_SERVER"
            echo $IMAGE_NAME "$IMAGE_NAME"
            mkdir -p project
            docker build -t $REGISTRY_SERVER/$IMAGE_NAME .
            docker login -u $REGISTRY_UN -p $REGISTRY_PW $REGISTRY_SERVER
            docker push $REGISTRY_SERVER/$IMAGE_NAME
            docker rmi -f $REGISTRY_SERVER/$IMAGE_NAME
#            - save_cache:
#                name: Save Yarn Package Cache
#                key: yarn-packages-{{ checksum "yarn.lock" }}
#                paths:
#                  - ~/.cache/yarn
#            - persist_to_workspace:
#                root: ~/project
#                paths:
#                  - Dockerfile
#                  - version
#  deploy-to-prod:
#      machine: true
#      steps:
#        - checkout
#        - attach_workspace:
#            at: workspace
#        - run:
#            name: deploy ycom
#            command: |
#              TAG=`cat workspace/version`
#              docker login -u $REGISTRY_UN -p $REGISTRY_PW $REGISTRY_SERVER
#              docker run --rm -it -e TF_VAR_repo_branch=$CIRCLE_BRANCH
#  workflows:
#    build-and-publish-docker-image:
#      jobs:
#        - build:
#        - deploy-to-prod:
#            requires:
#              -build